services:
  - type: web
    name: controle-veiculos
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: 'arcatech-controle-portaria-2026-secret-key'
      - key: DATABASE_URL
        sync: false
