CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS registros (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios(id),
  chegada VARCHAR(10) NOT NULL,
  placa VARCHAR(20) NOT NULL,
  modelo VARCHAR(100) DEFAULT '',
  finalidade VARCHAR(100) DEFAULT '',
  empresa VARCHAR(200) NOT NULL,
  motorista VARCHAR(200) DEFAULT '',
  cnh VARCHAR(50) DEFAULT '',
  entrada VARCHAR(10) NOT NULL,
  saida VARCHAR(10) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  data_registro DATE DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS motoristas (
  id SERIAL PRIMARY KEY,
  motorista VARCHAR(200) NOT NULL,
  cnh VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT ''
);

-- Usuários serão criados pelo servidor na inicialização

INSERT INTO motoristas (motorista, cnh, placa, empresa) VALUES
  ('RICARDO CAVATI', '959.320.207-25', 'LRW2F92', 'LIMPEZA PROFUNDA'),
  ('JOAO PAULO LEITE DA SILVA', '264.586.978-56', 'RQP2F23', 'VIX'),
  ('CARLOS SEVERINO', '798.904.667-91', 'RKU8J82', 'FILADELFIA'),
  ('GUILHERME RIBEIRO', '206.599.317-02', 'SRX5G20', 'FÊNIX DO BRASIL'),
  ('LUCIANO DOS SANTOS', '057.451.987-45', 'RQR2B64', 'FILADELFIA'),
  ('CARLOS ALBERTO DE SOUZA', '955.254.677-04', 'LUD1906', 'SUPERGASBRAS'),
  ('PEDRO PAULO SILVA', '129.424.276-80', 'SRX5G20', 'FÊNIX DO BRASIL'),
  ('FLÁVIO DE AZEVEDO', '087.380.117-27', 'KYK3172', 'RODOMAC'),
  ('JEAN DA SILVA PERES', '112.824.157-94', 'KPE1932', 'FILADELFIA'),
  ('WANDERSON DE PAULA', '073.101.187-23', 'JQR5A35', 'S.O.S'),
  ('ANDERSON DA SILVA', '097.349.547-25', 'LLJ9A08', 'TRANSFORMA'),
  ('CRISTIANO GONÇALVES LINS', '051.498.747-28', 'KYK3172', 'RODOMAC'),
  ('DENILSON PECANHA PASSOS', '074.503.697-02', 'RKUTI22', 'VIX'),
  ('DAVI DA CONCEICAO SILVA', '097.299.017-83', 'QUC0J07', 'JAMEF'),
  ('JOSE ELIAS SOARES', '681.074.717-68', 'QRF9E51', 'VIX'),
  ('DANIEL GASPAR', '098.082.987-96', '', 'EFITRANS'),
  ('CESAR LINO BAPTISTA JUNIOR', '088.796.297-46', 'RMY5J26', 'LB SOLDAS'),
  ('ALISON DE OLIVEIR DA SILVA', '133.921.527-65', 'LMA2C60', 'FILADELFIA'),
  ('MARCOS VENICIUS AZEREDO', '915.940.737-91', 'SRK2D09', 'AEROSTEEL'),
  ('ADRIELE ANTUNES', '171.517.797-55', 'LQM6B95', 'GRUPO TROCA'),
  ('ROBERTO CARLOS', '976.126.007-06', 'PTO0G19', 'FILADELFIA'),
  ('PAULO CEZAR', '709.650.087-62', 'TTZ82C41', 'FILADELFIA'),
  ('PATRICK CARVALHO', '014.732.826-38', 'RUI1J33', 'FILADELFIA'),
  ('ROBSON CARLOS', '36382071', 'RJF9E28', 'FILADELFIA')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS visitantes (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios(id),
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  tipo VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  entrada VARCHAR(10) NOT NULL,
  saida VARCHAR(10) DEFAULT '',
  data_registro DATE DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE registros ADD COLUMN IF NOT EXISTS posicao INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS pre_registros (
  id SERIAL PRIMARY KEY,
  empresa VARCHAR(200) NOT NULL,
  motorista VARCHAR(200) NOT NULL,
  cnh VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) NOT NULL,
  modelo VARCHAR(100) DEFAULT '',
  finalidade VARCHAR(100) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contas_motoristas (
  id SERIAL PRIMARY KEY,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contas_visitantes (
  id SERIAL PRIMARY KEY,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pre_registros_visitantes (
  id SERIAL PRIMARY KEY,
  visitante_id INTEGER REFERENCES contas_visitantes(id),
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  tipo VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
  id SERIAL PRIMARY KEY,
  empresa VARCHAR(200) NOT NULL,
  cnpj VARCHAR(20) DEFAULT '',
  responsavel VARCHAR(200) DEFAULT '',
  email VARCHAR(200) DEFAULT '',
  telefone VARCHAR(20) DEFAULT '',
  plano VARCHAR(50) DEFAULT 'basico',
  valor_mensal DECIMAL(10,2) DEFAULT 0,
  data_inicio DATE DEFAULT CURRENT_DATE,
  data_expiracao DATE,
  ativo BOOLEAN DEFAULT TRUE,
  dominio VARCHAR(200) DEFAULT '',
  db_url VARCHAR(500) DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faturamento (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id),
  valor DECIMAL(10,2) NOT NULL,
  descricao VARCHAR(200) DEFAULT '',
  data_pagamento DATE DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
