CREATE TABLE IF NOT EXISTS clientes (
  id SERIAL PRIMARY KEY,
  empresa VARCHAR(200) NOT NULL,
  cnpj VARCHAR(20) DEFAULT '',
  responsavel VARCHAR(200) DEFAULT '',
  email VARCHAR(200) DEFAULT '',
  telefone VARCHAR(20) DEFAULT '',
  telefone_fixo VARCHAR(20) DEFAULT '',
  plano VARCHAR(50) DEFAULT 'basico',
  valor_mensal DECIMAL(10,2) DEFAULT 0,
  data_inicio DATE DEFAULT CURRENT_DATE,
  data_expiracao DATE,
  ativo BOOLEAN DEFAULT TRUE,
  dominio VARCHAR(200) DEFAULT '',
  db_url VARCHAR(500) DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  usuario VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  nome VARCHAR(100) NOT NULL,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(cliente_id, usuario)
);

CREATE TABLE IF NOT EXISTS registros (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  usuario_id INTEGER REFERENCES usuarios(id),
  chegada VARCHAR(10) NOT NULL,
  placa VARCHAR(20) NOT NULL,
  modelo VARCHAR(100) DEFAULT '',
  finalidade VARCHAR(100) DEFAULT '',
  empresa VARCHAR(200) NOT NULL,
  motorista VARCHAR(200) DEFAULT '',
  cnh VARCHAR(50) DEFAULT '',
  entrada VARCHAR(10) NOT NULL,
  saida VARCHAR(10) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  posicao INTEGER DEFAULT 0,
  data_registro DATE DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS motoristas (
  id SERIAL PRIMARY KEY,
  motorista VARCHAR(200) NOT NULL,
  cnh VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS pre_registros (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  empresa VARCHAR(200) NOT NULL,
  motorista VARCHAR(200) NOT NULL,
  cnh VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) NOT NULL,
  modelo VARCHAR(100) DEFAULT '',
  finalidade VARCHAR(100) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contas_motoristas (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  empresa VARCHAR(200) DEFAULT '',
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(cliente_id, usuario)
);

CREATE TABLE IF NOT EXISTS contas_visitantes (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  senha_exibicao VARCHAR(100) DEFAULT '',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(cliente_id, usuario)
);

CREATE TABLE IF NOT EXISTS visitantes (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  usuario_id INTEGER REFERENCES usuarios(id),
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  tipo VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs VARCHAR(500) DEFAULT '',
  entrada VARCHAR(10) NOT NULL,
  saida VARCHAR(10) DEFAULT '',
  data_registro DATE DEFAULT CURRENT_DATE,
  posicao INTEGER DEFAULT 0,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pre_registros_visitantes (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  visitante_id INTEGER REFERENCES contas_visitantes(id),
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) DEFAULT '',
  empresa VARCHAR(200) DEFAULT '',
  tipo VARCHAR(50) DEFAULT '',
  placa VARCHAR(20) DEFAULT '',
  nota VARCHAR(100) DEFAULT '',
  obs TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faturamento (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  valor DECIMAL(10,2) NOT NULL,
  descricao VARCHAR(200) DEFAULT '',
  data_pagamento DATE DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs_acesso (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER,
  admin_usuario VARCHAR(100) DEFAULT '',
  acao VARCHAR(200) NOT NULL,
  detalhes TEXT DEFAULT '',
  ip VARCHAR(100) DEFAULT '',
  user_agent TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chamados (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  titulo VARCHAR(200) NOT NULL,
  descricao TEXT DEFAULT '',
  status VARCHAR(20) DEFAULT 'aberto',
  prioridade VARCHAR(20) DEFAULT 'media',
  resposta TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historico_clientes (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE SET NULL,
  admin_usuario VARCHAR(100) DEFAULT '',
  acao VARCHAR(200) NOT NULL,
  detalhes TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS config_geral (
  chave VARCHAR(100) PRIMARY KEY,
  valor TEXT DEFAULT '',
  descricao VARCHAR(200) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS logs_auditoria (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER REFERENCES clientes(id) ON DELETE CASCADE,
  usuario VARCHAR(100) DEFAULT '',
  acao VARCHAR(100) NOT NULL,
  tipo VARCHAR(50) DEFAULT '',
  alvo VARCHAR(200) DEFAULT '',
  detalhes TEXT DEFAULT '',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
